baseURL = "https://johannes.arnold.onl/"
languageCode = "en-US"
title = "Johannes Karl Arnold"
copyright = "&copy; Johannes Arnold."
theme = "github.com/jpanther/congo/v2"
# sectionPagesMenu = "main"
enableGitInfo = true

[permalinks]
    post = '/post/:year/:slug/'
